export const SETTING: Record<string, string> = {
"**customGreeting": "text",
"**dayStartTime": "time",
"**dayFormat": "text",
"**timeFormat": "text",
"**appNickname": "text",
"**selfNickname": "text",
"**settingsFolder": "text",
"**colourScheme": "text",
"**listEntryCount": "number",
"**showCount": "number",
"*reloadPurchases": "locked",
"*unlockThemes": "locked",
"*unlockAPI": "locked",
"*unlockSlots": "locked",
"UUID": "locked",
}